[dispatcher]
id = "dispatcher1-ff00_0_112-eh"
application_socket = "/run/shm/dispatcher/endhost1-ff00_0_112.sock"
socket_file_mode = "0777"

[metrics]
prometheus = "[10.248.6.1]:30441"

[features]

[log.console]
level = "debug"
