[general]
id = "sd1-ff00_0_111"
config_dir = "gen/ASff00_0_111"
reconnect_to_dispatcher = true

[trust_db]
connection = "gen-cache/sd1-ff00_0_111.trust.db"

[path_db]
connection = "gen-cache/sd1-ff00_0_111.path.db"

[sd]
address = "10.0.0.77:30255"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "10.0.0.77:30455"

[features]

[api]
addr = "10.0.0.77:30955"

[drkey_level2_db]
connection = "gen-cache/sd1-ff00_0_111.drkey_level2.db"

[log.console]
level = "debug"
