[general]
id = "cs1-ff00_0_110-1"
config_dir = "gen/ASff00_0_110"
reconnect_to_dispatcher = true

[trust_db]
connection = "gen-cache/cs1-ff00_0_110-1.trust.db"

[beacon_db]
connection = "gen-cache/cs1-ff00_0_110-1.beacon.db"

[path_db]
connection = "gen-cache/cs1-ff00_0_110-1.path.db"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "10.10.0.69:30452"

[features]

[log.console]
level = "debug"
