[general]
id = "sd1-ff00_0_110"
config_dir = "gen/ASff00_0_110"
reconnect_to_dispatcher = true

[trust_db]
connection = "gen-cache/sd1-ff00_0_110.trust.db"

[path_db]
connection = "gen-cache/sd1-ff00_0_110.path.db"

[sd]
address = "10.10.0.70:30255"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "10.10.0.70:30455"

[features]

[log.console]
level = "debug"
