[general]
id = "sd1-ff00_0_111-eh"
config_dir = "gen-eh/ASff00_0_111"
reconnect_to_dispatcher = true

[trust_db]
connection = "gen-cache/sd1-ff00_0_111-eh.trust.db"

[path_db]
connection = "gen-cache/sd1-ff00_0_111-eh.path.db"

[sd]
address = "10.1.1.11:30255"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "10.1.1.11:30455"

[features]

[api]
addr = "10.1.1.11:30955"

[drkey_level2_db]
connection = "gen-cache/sd1-ff00_0_111-eh.drkey_level2.db"

[log.console]
level = "debug"
