[general]
id = "cs1-ff00_0_131-1"
config_dir = "gen/ASff00_0_131"
reconnect_to_dispatcher = true

[trust_db]
connection = "gen-cache/cs1-ff00_0_131-1.trust.db"

[beacon_db]
connection = "gen-cache/cs1-ff00_0_131-1.beacon.db"

[path_db]
connection = "gen-cache/cs1-ff00_0_131-1.path.db"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "10.0.0.132:30452"

[api]
addr = "10.0.0.132:31152"

[features]

[log.console]
level = "debug"

[drkey.level1_db]
connection = "gen-cache/cs1-ff00_0_131-1.drkey_level1.db"

[drkey.secret_value_db]
connection = "gen-cache/cs1-ff00_0_131-1.secret_value.db"
